name: Publish to PyPI

on:
  push:
    # Pattern matched against refs/tags
    tags:
    - "**"  # Push events to every tag including tags with slashes

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  run-testpypi-tests:
    name: Test TestPyPI on ClickHouse
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: yandex/clickhouse-server
        ports:
          - 9000/tcp
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install airflow-clickhouse-plugin from TestPyPI
        run: |
          python -m pip install --upgrade pip
          python -m pip install \
            --index-url https://test.pypi.org/simple \
            --extra-index-url https://pypi.org/simple \
            airflow-clickhouse-plugin[common.sql]==1.1.0
      - name: Run tests on ClickHouse server
        env:
          AIRFLOW_CONN_CLICKHOUSE_DEFAULT: "clickhouse://localhost:${{ job.services.clickhouse.ports['9000'] }}"
        run: |
          cd tests  # run tests using pip-installed version
          python -m unittest

  publish-to-pypi:
    name: Publish to PyPI
    needs:
    - build
    - run-testpypi-tests
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/airflow-clickhouse-plugin
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download distribution packages
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  run-pypi-tests:
    name: Test PyPI on ClickHouse
    runs-on: ubuntu-latest
    needs:
      - publish-to-pypi
    services:
      clickhouse:
        image: yandex/clickhouse-server
        ports:
          - 9000/tcp
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install airflow-clickhouse-plugin from PyPI
        run: |
          python -m pip install --upgrade pip
          python -m pip install airflow-clickhouse-plugin[common.sql]==1.1.0
      - name: Run tests on ClickHouse server
        env:
          AIRFLOW_CONN_CLICKHOUSE_DEFAULT: "clickhouse://localhost:${{ job.services.clickhouse.ports['9000'] }}"
        run: |
          cd tests  # run tests using pip-installed version
          python -m unittest

  upload-to-github-release:
    name: Sign and upload to GitHub Release
    needs:
    - publish-to-pypi
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
    - name: Download distribution packages
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Sign with Sigstore
      uses: sigstore/gh-action-sigstore-python@v1.2.3
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Upload to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'
